ingress:
  enabled: true
  hosts:
   - kibana.plgrnd.be
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
  tls:
   - hosts:
      - kibana.plgrnd.be
     secretName: kibana-tls

