apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: custom-alertmanager
  namespace: cattle-prometheus
spec:
  baseImage: rancher/prom-alertmanager
  version: v0.21.0
  replicas: 1
  listenLocal: false
  serviceAccountName: custom-alertmanager
  externalUrl: http://alertmanager-operated.cattle-prometheus:9093
  paused: false
  logFormat: "logfmt"
  logLevel:  "info"
  retention: "120h"
  resources:
    limits:
      cpu: 1000m
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 50Mi
  routePrefix: "/"
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  portName: web
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-alertmanager
  namespace: cattle-prometheus