volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 5Gi

ingress:
  enabled: true
  hosts:
   - host: es.k8s-demo.plgrnd.be
     paths:
       - path: /
  annotations:
    cert-manager.io/issuer: my-ca-issuer
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
  tls:
   - hosts:
      - es.k8s-demo.plgrnd.be
     secretName: es-tls

