ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  rules:
    - host: keycloak.k8s-demo.plgrnd.be
      paths:
        - /
  tls:
    - hosts:
        - keycloak.k8s-demo.plgrnd.be
      secretName: keycloak-tls

extraEnv: |
  - name: KEYCLOAK_USER
    value: admin
  - name: KEYCLOAK_PASSWORD
    value: admin
  - name: JAVA_OPTS
    value: >-
      -Dkeycloak.frontendUrl=https://keycloak.k8s-demo.plgrnd.be/auth