apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
        - name: abcd
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              port: http
              path: /
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: nginx-www
      volumes:
        - name: nginx-www
          persistentVolumeClaim:
            claimName: nginx-www
