apiVersion: v1
# this must be base64 encoded
data:
  access-token: ZDVkZjViZWQzMjY5YTM3ZGZlZjk5ZmIyNjY3YjVjZDFjNDAwYzE4YTVkMjhjY2E5OTRmYWZkNTdkYjczMTlhZA==
kind: Secret
metadata:
  name: digitalocean-credentials-secret
  namespace: cert-manager
type: Opaque
