apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: shop-tls-certificate
  namespace: istio-system
spec:
  dnsNames:
  - shop.istio.plgrnd.be
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: shop-tls-certificate-certs