orchestrator:
  config:
    # `reset slave all` and `set read_only=0` on promoted master
    ApplyMySQLPromotionAfterMasterFailover: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
    hosts:
    - host: mysql-operator.k8s-demo.plgrnd.be
      paths:
        - /
    tls:
      - secretName: mysql-operator-tls
        hosts:
          - mysql-operator.k8s-demo.plgrnd.be