apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bookinfo-tls-certificate
  namespace: istio-system
spec:
  dnsNames:
  - bookinfo.k8s-demo.plgrnd.be
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: bookinfo-tls-certificate-certs